theme[main_bg]="#282828"
theme[main_fg]="#49a12e"

theme[title]="#e1d949"
theme[hi_fg]="#e1d949"
theme[selected_bg]="#1C1C1C"
theme[selected_fg]="#e1d949"

theme[inactive_fg]="#a0a0a0"
theme[graph_text]="#9cac9c"
theme[meter_bg]="#050c01"

theme[proc_misc]="#eea059"

theme[cpu_box]="#49a12e"
theme[mem_box]="#e1d949"
theme[net_box]="#30588c"
theme[proc_box]="#eea059"

theme[div_line]="#a0a0a0"

theme[temp_start]="#49a12e"
theme[temp_mid]="#e1d949"
theme[temp_end]="#C30100"

theme[cpu_start]="#49a12e"
theme[cpu_mid]="#e1d949"
theme[cpu_end]="#C30100"

theme[free_start]="#050c01"
theme[free_mid]="#49a12e"
theme[free_end]="#3CF800"

theme[cached_start]="#907824"
theme[cached_mid]="#eea059"
theme[cached_end]="#e1d949"

theme[available_start]="#30588c"
theme[available_mid]="#406c8c"
theme[available_end]="#9cac9c"

theme[used_start]="#e1d949"
theme[used_mid]="#eea059"
theme[used_end]="#C30100"

theme[download_start]="#30588c"
theme[download_mid]="#406c8c"
theme[download_end]="#9cac9c"

theme[upload_start]="#907824"
theme[upload_mid]="#eea059"
theme[upload_end]="#e1d949"
