theme[main_bg]="#000000"
theme[main_fg]="#c2c3c7"

theme[title]="#f3ef7d"
theme[hi_fg]="#ffec27"
theme[selected_bg]="#ffec27"
theme[selected_fg]="#000000"

theme[inactive_fg]="#5f574f"
theme[graph_text]="#a8e72e"
theme[meter_bg]="#000000"

theme[proc_misc]="#ff77a8"

theme[cpu_box]="#00e436"
theme[mem_box]="#ffec27"
theme[net_box]="#29adff"
theme[proc_box]="#ff004d"

theme[div_line]="#5f574f"

theme[temp_start]="#00e436"
theme[temp_mid]="#ffec27"
theme[temp_end]="#ff004d"

theme[cpu_start]="#00e436"
theme[cpu_mid]="#ffec27"
theme[cpu_end]="#ff004d"

theme[free_start]="#008751"
theme[free_mid]="#00e436"
theme[free_end]="#a8e72e"

theme[cached_start]="#be1250"
theme[cached_mid]="#ff77a8"
theme[cached_end]="#f3ef7d"

theme[available_start]="#29adff"
theme[available_mid]="#c2c3c7"
theme[available_end]="#fff1e8"

theme[used_start]="#ffec27"
theme[used_mid]="#ff77a8"
theme[used_end]="#ff004d"

theme[download_start]="#29adff"
theme[download_mid]="#c2c3c7"
theme[download_end]="#fff1e8"

theme[upload_start]="#ff77a8"
theme[upload_mid]="#f3ef7d"
theme[upload_end]="#fff1e8"
